[package]
name = "atlas77-std"
# The version will follow the compiler version
# At one point, if you have a 0.x compiler, but a 0.y std, it shouldn't directly work
# The compiler should pull only its linked stdlib
version = "0.9.0"
entry = "src/main.atlas"
compiler = "gcc"
args = ["-std=c2y"]

[c]
include_dirs = ["include/"]
headers = ["atlas77_std_c_impl.h"]

[c.windows]
include_dirs = []
headers = []

[c.linux]
lib_dirs = []
